### ISSUE TITLE
gnome-books not loading epub files in fedora 22 gnome 3.15.90

### ISSUE THREAD

**Issue by fastrizwaan** [martamilakovic/gnome-books#6]
it is showing the epub files, but on opening, it hangs.

**Comment by l-ray** [comment]
It tells me when trying to open a epub, as this is a preview, the epub integration will come later.

**Comment by jordanpavlov** [comment]
Hymm what files can it open as a book reader now? I assumed it could open epub as such. As specially as it has links to https://github.com/danigm/libgepub and https://github.com/futurepress/epub.js/ that supposedly are used and are able to do exactly that? All of those are put no the official gnome wiki link https://wiki.gnome.org/Outreach/SummerOfCode/2014/Projects/MartaMilakovic_GnomeBooks
Wait, Outreach. Oh

**Comment by fastrizwaan** [comment]
Exactly after 1 year, I'm asking the same thing, "it can't open epub files...!?"

How soon is soon?

**Comment by miguxbe** [comment]
I think that the project could be considered as 'abandonware'. Marta told me otherwise, the project is not abandoned but was "merged" into gnome-documents. Yep, a little bit confusing. https://git.gnome.org/browse/gnome-documents/tree/data/org.gnome.Books.appdata.xml.in

**Comment by martamilakovic** [comment]
Hi,
Thanks for your interest. Yeah, as you can see, project have been on pause for a while, due to overload of work, school and other obligations. I would love to get back to it and finish work :)

**Comment by webmaven** [comment]
@martamilakovic, do you think that you are likely to ever get back to developing this project? At this point it has been two-and-a-half years since the last commit.

**Comment by martamilakovic** [comment]
@webmaven, it is unlikly that I will be able to get back to the project any time soon. Work and other projects are taking all of my time at the moment.

**Comment by fastrizwaan** [comment]
Linux has only incomplete ebook readers. Good epub readers we can use are available as firefox addons (or others as chrome extensions);  Android has all the good ebook readers (I love moonreader+)

This one can load epub files and looks pretty (but  is feature incomplete)
 https://github.com/michaldaniel/Ebook-Viewer

firefox addon (the best) not so good looking but functional.
https://www.epubread.com/en/screens.php
